# coding: utf-8

"""
    Swagger Bearsapi (Simple)

    A sample API that uses a bears=mongostore as an example to demonstrate features in the swagger-2.0 specification

    OpenAPI spec version: 1.0.1
    Contact: foo@example.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import ApiClient
from .api_client import ApiClient
# import apis into sdk package
from .apis.default_api import DefaultApi
from .configuration import Configuration
# import models into sdk package
from .models.bear import Bear
from .models.error_model import ErrorModel
from .models.new_bear import NewBear

configuration = Configuration()
