# coding: utf-8

"""
    Swagger Bearsapi (Simple)

    A sample API that uses a bears=mongostore as an example to demonstrate features in the swagger-2.0 specification

    OpenAPI spec version: 1.0.1
    Contact: foo@example.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from .bear import Bear
from .error_model import ErrorModel
from .new_bear import NewBear
